[build]
  command = "echo 'No build needed'"
  publish = "."

[functions]
  directory = "netlify/functions"

# Scheduled Functions - Automatic morning crawl at 06:00 UTC
# [[functions.scheduled]]
#   function = "scheduled-crawl"
#   schedule = "0 6 * * *"  # Every day at 06:00 UTC (08:00 Norwegian time)

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self' https://askerfotball.no https://*.entity.no https://*.entity.com"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Cache-Control = "no-cache"