[build]
  # Netlify vil automatisk bygge og deploye statiske filer
  publish = "."
  
  # Edge Functions konfigurasjon
  [build.functions]
    directory = "netlify/functions"

# Edge Functions settings
[functions]
  # Timeout for Edge Functions (maks 10 sekunder)
  timeout = 10

# Redirect rules for SPA-like behavior (valgfritt)
[[redirects]]
  from = "/"
  to = "/askerbot-demo.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for CORS og sikkerhet
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Cache-Control = "no-cache"

# Sikkerhetsheaders for hele siden
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (settes i Netlify dashboard)
# OPENAI_API_KEY = "sk-..."
